#!/usr/bin/env python3
"""Generate functions/_lib/catalog.js (compact catalogue for the server-rendered SEO pages) from index.html.

index.html is the source of truth. Re-run after every catalogue change:  python scripts/gen_catalog.py
Row format (see functions/_lib/site.js):
  [id, title, brand, cat, platform, seller, usd, cny, qc, best, views, img, g, itemId, variants]
img is stored with a short host prefix (A/B/C = the Supabase storage hosts) to keep the bundle small.
"""
import datetime, json, re, sys

PREFIX = {
    "A": "https://uiiegkpjqtgrkazccinf.supabase.co/storage/v1/object/public/",
    "B": "https://uptpghuduqjqmrxwatbm.supabase.co/storage/v1/object/public/",
    "C": "https://ckiynlgfmlvlyaozuduc.supabase.co/storage/v1/object/public/",
}

def read_catalog_items(html):
    """Catalogue items from index.html: a <script type="application/json" id="pc-catalog"> block
    (current format), or the older JS object literal inside loadProducts()."""
    tag = '<script type="application/json" id="pc-catalog">'
    i = html.find(tag)
    if i >= 0:
        j = html.find("</script>", i)
        return json.loads(html[i + len(tag):j])
    start = html.find("return [", html.find("function loadProducts()"))
    if start < 0:
        sys.exit("catalogue not found in index.html")
    start += len("return ")
    end = html.find("];", start) + 1
    return json.loads(re.sub(r'([{,])([A-Za-z_]\w*):', r'\1"\2":', html[start:end]))


def main():
    html = open("index.html", encoding="utf-8").read()
    items = read_catalog_items(html)
    b0 = html.find("const PC_BEST"); best = set(re.findall(r'"(\d+)"', html[b0:html.find("]);", b0)]))
    v0 = html.find("VIEW_COUNTS"); views = {}
    if v0 >= 0:
        blk = html[v0:html.find("}", v0)]
        views = {k: int(v) for k, v in re.findall(r'"?(\d{5,})"?\s*:\s*(\d+)', blk)}
    rows = []
    for p in items:
        img = p.get("img") or ""
        for k, pre in PREFIX.items():
            if img.startswith(pre): img = k + img[len(pre):]; break
        variants = "|".join(v[0] for v in (p.get("variants") or []) if v and v[0])[:160]
        rows.append([p["id"], p.get("title", ""), p.get("brand", ""), p.get("cat", ""), p.get("platform", "weidian"),
                     p.get("seller", ""), round(float(p.get("usd") or 0), 2), p.get("price") or 0, int(p.get("qc") or 0),
                     1 if p["id"] in best else 0, int(p.get("views") or views.get(p["id"], 0) or 0), img, p.get("g", ""),
                     p.get("itemId", ""), variants])
    out = ("// GENERATED by scripts/gen_catalog.py from index.html. Do not edit by hand.\n"
           "export const PREFIX = " + json.dumps(PREFIX) + ";\n"
           "export const BUILT = \"" + datetime.date.today().isoformat() + "\";\n"
           "export const ROWS = " + json.dumps(rows, ensure_ascii=False, separators=(",", ":")) + ";\n")
    open("functions/_lib/catalog.js", "w", encoding="utf-8").write(out)
    print("catalog rows:", len(rows), "best:", sum(r[9] for r in rows), "bytes:", len(out.encode()))

if __name__ == "__main__":
    main()
